### ISSUE TITLE
Getting the module id from the plugin correctly

### ISSUE THREAD

**Issue by sharpplayer** [rgoldberg/gradle-java-modules#12]
I would like to add some test support modules to my java compile in a multiproject situation (that is, the project definition has a `dependencies { implementation project(':testsupport')'}` [I also reckon here it should be testImplementation, but Gradle does not seem to be happy to use projects in the test* category, my dependency path messes up].

So I created an extension to the compileTestJava task thus:
```
compileTestJava {
      doFirst {
		if(inputs.properties.get("moduleNames") == null) {
			throw new GradleException("Must have a module-info.java")
		}
		else if(inputs.properties.get("moduleNames") != "") {
			throw new GradleException("Must have non-empty a module-info.java")
		}
		else {
				println "module:" + inputs.properties.get("moduleNames") + ":"
		}
		options.compilerArgs += ['--add-modules', 'testsupport]
  		options.compilerArgs += ['--add-reads', 'mymodulename=testsupport']
	}
}
```

But it seems the "moduleNames" property is not available in time to allow me to use it in the compiler options.  If you have any advice that would be greatly appreciated.

**Comment by rgoldberg** [comment]
You need to change the `!= “”` in the `else if` condition to `.isEmpty()`.

Your existing code incorrectly flipped `==` to `!=`; using `isEmpty()` is faster than `==`.

**Comment by rgoldberg** [comment]
Why do you check the value of `inputs.properties.get("moduleNames")`?

You don’t otherwise use it. You should be able to add the two module arguments to `compilerArgs` without any check.

**Comment by sharpplayer** [comment]
Thanks for that...what a stupid mistake!  Anyway, what I actually wanted to write in the above code was:
`options.compilerArgs += ['--add-reads', inputs.properties.get("moduleNames") + '=testsupport']` but I was just checking that "moduleNames" was actually a legitimate property to look at (especially as it is plural).  As I am using a multiproject setup, the module names are different for each project, so this is part of an "apply from" script that is imported into each modularised project.

**Comment by sharpplayer** [comment]
Something I did, I know not what, started resulting in blank module names...so I did a useless check which completely threw me.  I didn't actually look closely at the code I had written!

**Comment by rgoldberg** [comment]
Is everything working now?

**Comment by sharpplayer** [comment]
I wasn't going entirely mad...I have hit a problem where the module name is coming through as blank.  I do not know what could be special about the module-info.java to cause that, or even the project itself.  I "hacked" my compileTestJava task to pick out the module name thus:
```
compileTestJava {
      doFirst {
		def module = inputs.properties.get("moduleNames")
		if(module == null) {
			throw new GradleException("Must have a module-info.java")
		}
		else if(module.isEmpty()) {
			def finder = /(?<=module\s).*?(?=\s)/
			String fileContents = new File("${projectDir}/src/main/java/module-info.java").text
			//println fileContents
			module = (fileContents =~ finder)[0]
			//println fileContents + ":" + module;
			if(module.isEmpty()) {
				throw new GradleException("Must have non-empty module name in module-info.java")
			}
		}
		println "module:" + module + ":"
		options.compilerArgs += ['--add-modules', 'talon.testlogger']
		options.compilerArgs += ['--add-reads', "$module=talon.testlogger", "--add-reads", "$module=talon.testutil"]
	}
}
```

And my code _is_ picking up the module name correctly, even though the plugin is not.  So I do not know what could be happening...I'll take a look

**Comment by rgoldberg** [comment]
I only set moduleNames because the original plugin set moduleName (I pluralized it since my fork supports multiple modules per project). I haven’t really investigated its setting or usage, though.

**Comment by rgoldberg** [comment]
If you look at `JigsawPlugin`, there should be some instance fields that should contain module names, either indexed in a Map, or in a comma-delimited String. You could try to read from them if you can obtain the instance of the plugin from the `Project`. I don’t know how to do that, but guess that it can be done.

In the current version of IntelliJ, you can debug Gradle builds. I don’t know about other IDEs.

I can’t remember if the current code for the plugin matches what’s deployed on the Gradle Plugin Portal.

I can try to republish both the source & plugin binary sometime later. You might need to clear some Gradle caches to download the new SNAPSHOT once I’ve published it.

**Comment by sharpplayer** [comment]
It looks like there must have been some sort of corruption (maybe?) of the file...I opened it up in Notepad++ showing all hidden characters and it looked fine....I copied and pasted the contents to notepad, and resaved and it _seems_ to be working again, but I have no idea why

**Comment by rgoldberg** [comment]
Sounds like a problem with the java parser library I use. If you still have
a copy of the faulty file, please attach it here so I can try it

**Comment by sharpplayer** [comment]
Sadly it has got lost...if I encounter the problem again, I will attach it to this thread, but as far as I could see, there was nothing obvious.
